# general
seed: 42
num_workers: 8
dataset_dir: "./data"
device : 'cuda'
num_classes : 10

# train options
batch_size: 256
image_size: 64
start_epoch: 0
epochs: 20
dataset: "MNIST" # CIFAR-10 / CIFAR-100 / MNIST

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/LearningK/iter1" 
continue_before : False
metric : False

# loss options
learning_rate: 0.0003
weight_decay: None
instance_temperature: 0.5
cluster_temperature: 1.0
